// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLastScan() {
  return window['go']['main']['App']['GetLastScan']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function ImportAliyunConfig() {
  return window['go']['main']['App']['ImportAliyunConfig']();
}

export function IsBusy() {
  return window['go']['main']['App']['IsBusy']();
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function ListIssued() {
  return window['go']['main']['App']['ListIssued']();
}

export function ListSLBListeners(arg1) {
  return window['go']['main']['App']['ListSLBListeners'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartApply(arg1) {
  return window['go']['main']['App']['StartApply'](arg1);
}

export function StartDeploy(arg1) {
  return window['go']['main']['App']['StartDeploy'](arg1);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}
