// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {aliyun} from '../models';
import {main} from '../models';
import {store} from '../models';
import {deploy} from '../models';

export function ClearLogs():Promise<void>;

export function GetApplyProgress():Promise<aliyun.Progress>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDeployProgress():Promise<aliyun.Progress>;

export function GetLastScan():Promise<store.ScanResult>;

export function GetLogs():Promise<Array<main.TaskLog>>;

export function GetProgress():Promise<aliyun.Progress>;

export function ImportAliyunConfig():Promise<string>;

export function IsBusy():Promise<boolean>;

export function IsScanning():Promise<boolean>;

export function ListIssued():Promise<Array<store.IssuedCert>>;

export function ListSLBListeners(arg1:string):Promise<Array<deploy.ListenerInfo>>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function StartApply(arg1:Array<string>):Promise<string>;

export function StartDeploy(arg1:main.DeployRequest):Promise<string>;

export function StartScan():Promise<string>;

export function UploadCertToAliyun(arg1:string):Promise<string>;
